In [63]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

from talib.abstract import *
import pandas as pd
import os
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go
from datetime import datetime
import matplotlib.pyplot as plt
%matplotlib inline

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

df = pd.read_csv('merged_2010_2016.csv')
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')

df = df.loc[df['Ticker']=='AOT']
df = df.set_index('Date')

df['sma5'] = SMA(df, timeperiod=5, price='Close')
df['sma15'] = SMA(df, timeperiod=15, price='Close')
df.tail()

           Ticker   Open   High    Low  Close   Volume   sma5       sma15
Date
2016-12-26    AOT  391.0  397.0  390.0  394.0  2108000  390.2  394.533333
2016-12-27    AOT  395.0  395.0  392.0  393.0  2089200  390.6  394.266667
2016-12-28    AOT  394.0  395.0  393.0  394.0  1758200  391.6  393.933333
2016-12-29    AOT  395.0  398.0  394.0  396.0  3052900  393.0  393.666667
2016-12-30    AOT  397.0  400.0  397.0  398.0  2198000  395.0  393.800000

In [66]:
Hold = False
prev = 0
total = 0
for i, x in enumerate(df.iterrows()):
    
    date = x[0]
    sma5 = x[1]['sma5']
    sma15 = x[1]['sma15']
    close = x[1]['Close']
    
    if(sma5 > sma15 and not Hold):
        print(date, 'Buy:', close)
        Hold = True
        prev = close
        
    if(sma5 < sma15 and Hold):
        total += (close-prev)/100
        print(date, 'Sell:', close, ' net:', (close-prev)/100,'\n')
        Hold = False
print(total)

2010-01-22 00:00:00 Buy: 40.75
2010-01-27 00:00:00 Sell: 39.75  net: -0.01

2010-02-15 00:00:00 Buy: 39.25
2010-03-03 00:00:00 Sell: 38.5  net: -0.0075

2010-03-18 00:00:00 Buy: 38.5
2010-04-01 00:00:00 Sell: 38.5  net: 0.0

2010-05-06 00:00:00 Buy: 37.25
2010-05-18 00:00:00 Sell: 34.75  net: -0.025

2010-06-07 00:00:00 Buy: 34.25
2010-06-30 00:00:00 Sell: 34.0  net: -0.0025

2010-07-08 00:00:00 Buy: 35.5
2010-08-09 00:00:00 Sell: 39.5  net: 0.04

2010-08-11 00:00:00 Buy: 39.25
2010-08-27 00:00:00 Sell: 38.75  net: -0.005

2010-09-03 00:00:00 Buy: 39.25
2010-09-07 00:00:00 Sell: 39.25  net: 0.0

2010-09-23 00:00:00 Buy: 39.75
2010-10-07 00:00:00 Sell: 39.75  net: 0.0

2010-10-20 00:00:00 Buy: 40.0
2010-10-29 00:00:00 Sell: 39.0  net: -0.01

2010-11-26 00:00:00 Buy: 38.25
2011-01-06 00:00:00 Sell: 38.5  net: 0.0025

2011-02-14 00:00:00 Buy: 33.75
2011-02-23 00:00:00 Sell: 33.25  net: -0.005

2011-03-04 00:00:00 Buy: 34.5
2011-03-21 00:00:00 Sell: 34.0  net: -0.005

2011-03-25 00:00:00 Buy: 35.5
2011-05-03 00:00:00 Sell: 35.75  net: 0.0025

2011-05-19 00:00:00 Buy: 38.25
2011-06-07 00:00:00 Sell: 36.75  net: -0.015

2011-06-29 00:00:00 Buy: 35.0
2011-08-04 00:00:00 Sell: 46.75  net: 0.1175

2011-08-18 00:00:00 Buy: 46.0
2011-08-24 00:00:00 Sell: 44.5  net: -0.015

2011-08-30 00:00:00 Buy: 46.5
2011-09-15 00:00:00 Sell: 47.0  net: 0.005

2011-10-13 00:00:00 Buy: 39.25
2011-10-21 00:00:00 Sell: 37.25  net: -0.02

2011-11-03 00:00:00 Buy: 38.25
2011-11-07 00:00:00 Sell: 35.75  net: -0.025

2011-11-14 00:00:00 Buy: 40.5
2012-01-25 00:00:00 Sell: 48.5  net: 0.08

2012-01-26 00:00:00 Buy: 51.5
2012-02-20 00:00:00 Sell: 51.75  net: 0.0025

2012-03-05 00:00:00 Buy: 51.75
2012-04-05 00:00:00 Sell: 56.75  net: 0.05

2012-04-19 00:00:00 Buy: 58.0
2012-05-15 00:00:00 Sell: 59.75  net: 0.0175

2012-06-12 00:00:00 Buy: 57.25
2012-07-24 00:00:00 Sell: 64.5  net: 0.0725

2012-07-27 00:00:00 Buy: 65.25
2012-08-14 00:00:00 Sell: 66.5  net: 0.0125

2012-08-28 00:00:00 Buy: 66.0
2012-10-18 00:00:00 Sell: 85.75  net: 0.1975

2012-10-22 00:00:00 Buy: 86.0
2012-10-29 00:00:00 Sell: 79.0  net: -0.07

2012-11-12 00:00:00 Buy: 85.0
2013-03-22 00:00:00 Sell: 115.0  net: 0.3

2013-04-01 00:00:00 Buy: 120.5
2013-04-09 00:00:00 Sell: 112.5  net: -0.08

2013-04-18 00:00:00 Buy: 136.5
2013-06-06 00:00:00 Sell: 155.0  net: 0.185

2013-07-02 00:00:00 Buy: 165.0
2013-08-02 00:00:00 Sell: 178.5  net: 0.135

2013-09-06 00:00:00 Buy: 166.0
2013-09-27 00:00:00 Sell: 187.5  net: 0.215

2013-10-03 00:00:00 Buy: 198.0
2013-11-01 00:00:00 Sell: 206.0  net: 0.08

2013-11-15 00:00:00 Buy: 209.0
2013-11-22 00:00:00 Sell: 192.0  net: -0.17

2014-01-16 00:00:00 Buy: 166.0
2014-03-21 00:00:00 Sell: 192.5  net: 0.265

2014-04-02 00:00:00 Buy: 197.5
2014-04-11 00:00:00 Sell: 195.0  net: -0.025

2014-04-21 00:00:00 Buy: 192.5
2014-04-22 00:00:00 Sell: 193.0  net: 0.005

2014-04-24 00:00:00 Buy: 196.5
2014-05-08 00:00:00 Sell: 190.0  net: -0.065

2014-06-04 00:00:00 Buy: 195.0
2014-07-02 00:00:00 Sell: 197.0  net: 0.02

2014-07-15 00:00:00 Buy: 201.0
2014-08-04 00:00:00 Sell: 215.0  net: 0.14

2014-08-15 00:00:00 Buy: 216.0
2014-09-12 00:00:00 Sell: 241.0  net: 0.25

2014-09-23 00:00:00 Buy: 244.0
2014-10-02 00:00:00 Sell: 236.0  net: -0.08

2014-10-24 00:00:00 Buy: 236.0
2014-12-17 00:00:00 Sell: 266.0  net: 0.3

2015-01-08 00:00:00 Buy: 289.0
2015-02-13 00:00:00 Sell: 312.0  net: 0.23

2015-03-23 00:00:00 Buy: 303.0
2015-03-30 00:00:00 Sell: 280.0  net: -0.23

2015-04-16 00:00:00 Buy: 300.0
2015-04-27 00:00:00 Sell: 292.0  net: -0.08

2015-05-20 00:00:00 Buy: 301.0
2015-06-22 00:00:00 Sell: 296.0  net: -0.05

2015-07-03 00:00:00 Buy: 310.0
2015-07-17 00:00:00 Sell: 298.0  net: -0.12

2015-09-01 00:00:00 Buy: 274.0
2015-09-16 00:00:00 Sell: 277.0  net: 0.03

2015-09-30 00:00:00 Buy: 281.0
2015-11-30 00:00:00 Sell: 311.0  net: 0.3

2015-12-03 00:00:00 Buy: 320.0
2016-01-07 00:00:00 Sell: 337.0  net: 0.17

2016-01-18 00:00:00 Buy: 351.0
2016-02-15 00:00:00 Sell: 369.0  net: 0.18

2016-02-17 00:00:00 Buy: 396.0
2016-03-17 00:00:00 Sell: 402.0  net: 0.06

2016-04-19 00:00:00 Buy: 404.0
2016-05-04 00:00:00 Sell: 394.0  net: -0.1

2016-05-24 00:00:00 Buy: 394.0
2016-06-01 00:00:00 Sell: 390.0  net: -0.04

2016-06-23 00:00:00 Buy: 392.0
2016-07-11 00:00:00 Sell: 385.0  net: -0.07

2016-07-22 00:00:00 Buy: 393.0
2016-08-22 00:00:00 Sell: 402.0  net: 0.09

2016-09-19 00:00:00 Buy: 402.0
2016-09-29 00:00:00 Sell: 397.0  net: -0.05

2016-09-30 00:00:00 Buy: 399.0
2016-10-03 00:00:00 Sell: 398.0  net: -0.01

2016-10-27 00:00:00 Buy: 383.0
2016-11-03 00:00:00 Sell: 372.0  net: -0.11

2016-11-25 00:00:00 Buy: 383.0
2016-12-20 00:00:00 Sell: 391.0  net: 0.08

2016-12-30 00:00:00 Buy: 398.0
2.1400000000000015